name: local-project
services:
  app:
    container_name: app
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - DEV_MODE=app
    networks:
      - public
networks:
  public:
    external: true