name: local-project
services:
  study-go:
    container_name: study-go
    restart: always
    build:
      context: ./
      dockerfile: ./app/Dockerfile
      args:
        - DEV_MODE
    networks:
      - public
networks:
  public:
    external: true