name: project
services:
  app:
    container_name: app
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DSN=postgres://postgres:123456@postgresql:5432/postgres
    networks:
      - public
networks:
  public:
    external: true