// Code generated by goctlx. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/go-template/app/logic"
	"github.com/go-template/app/svc"
	"github.com/go-template/app/types"
	"github.com/zeromicro/go-zero/rest/httpx"
)

func LoginHandler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.LoginReq
		if err := httpx.Parse(r, &req); err != nil {
			httpx.ErrorCtx(r.Context(), w, err)
			return
		}

		l := logic.NewAppLogic(r.Context(), svcCtx, r, &w)
		resp, err := l.Login(&req)
		if err != nil {
			if respErr, ok := err.(*logic.ResponseDataError); ok {
				httpx.WriteJson(w, respErr.Code, respErr.Data)
			} else {
				l.Error(err)
				httpx.ErrorCtx(r.Context(), w, err)
			}
		} else {
			httpx.OkJsonCtx(r.Context(), w, resp)
		}
	}
}
