// Code generated by goctlx. DO NOT EDIT.

package handler

import (
	"net/http"

	"github.com/go-template/app/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				// 注册用户
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				// 用户详情
				Method:  http.MethodGet,
				Path:    "/userinfo/:id",
				Handler: UserInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)
}
