// Code generated by goctlx. DO NOT EDIT.

package dbmodels

import (
	"time"
)

const TableNameUsers = "users"

// Users
type Users struct {
	Id           int32      `gorm:"column:id;primaryKey" json:"id,omitempty"`
	Username     string     `gorm:"column:username" json:"username,omitempty"`
	Email        string     `gorm:"column:email" json:"email,omitempty"`
	PasswordHash string     `gorm:"column:password_hash" json:"password_hash,omitempty"`
	FirstName    string     `gorm:"column:first_name" json:"first_name,omitempty"`
	LastName     string     `gorm:"column:last_name" json:"last_name,omitempty"`
	IsActive     *bool      `gorm:"column:is_active" json:"is_active,omitempty"`
	CreatedAt    *time.Time `gorm:"column:created_at" json:"created_at,omitempty"`
	UpdatedAt    *time.Time `gorm:"column:updated_at" json:"updated_at,omitempty"`
}

// TableName Users's table name
func (*Users) TableName() string {
	return TableNameUsers
}
