// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	UserName string `form:"userName",options`
	Password string `form:"password"`
	Mobile   string `form:"mobile"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type UserInfoRequest struct {
	Tag      string `path:"tag,options=you|me"`
	Password string `json:"password,optional"`
	Age      uint   `json:"age,range=[0:100]"`
	Gender   string `json:"gender,default=male"`
}

type UserInfoResponse struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
	Id       uint   `json:"id"`
}
