// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	UserName string `form:"userName,optional"` // 用户
	Password string `form:"password"`          // 密码
	Mobile   string `form:"mobile"`            // 手机号
}

type UserInfoRequest struct {
	Tag      string `path:"tag,options=you|me"`
	Password string `json:"password,optional"`
	Age      uint   `json:"age,range=[0:100]"`
	Gender   string `json:"gender,default=male"`
}

type UserInfoResponse struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
	Id       uint   `json:"id"`
}
