// Package dbmodel Code generated by sql2struct. https://github.com/dxc0522/sql2struct
package dbmodel

import "time"

type Users struct {
	ID       int64     `gorm:"column:id" json:"id,omitempty"`
	Name     string    `gorm:"column:name" json:"name,omitempty"`
	Password string    `gorm:"column:password" json:"password,omitempty"`
	Mobile   string    `gorm:"column:mobile" json:"mobile,omitempty"`
	CrateAt  time.Time `gorm:"column:crate_at" json:"crate_at,omitempty"`
}

// TableName the name of table in database
func (t *Users) TableName() string {
	return "users"
}
