// Code generated by goctlx. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/go-template/common/pkg/errorx"
	"github.com/go-template/demo/logic"
	"github.com/go-template/demo/svc"
	"github.com/go-template/demo/types"
	"github.com/zeromicro/go-zero/rest/httpx"
)

func DemoHandler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.Request
		if err := httpx.Parse(r, &req); err != nil {
			httpx.ErrorCtx(r.Context(), w, err)
			return
		}

		l := logic.NewDemoLogic(r.Context(), svcCtx, r, &w)
		resp, err := l.Demo(&req)
		if err != nil {
			if respErr, ok := err.(*errorx.ResponseError); ok {
				httpx.WriteJson(w, respErr.Code, respErr.Data)
			} else {
				l.Error(err)
				httpx.ErrorCtx(r.Context(), w, err)
			}
		} else {
			httpx.OkJsonCtx(r.Context(), w, resp)
		}
	}
}
