// Code generated by goctlx. DO NOT EDIT.

package types

type LoginReq struct {
	Email    string `json:"email,example:admin@example.com"` // 邮箱
	Password string `json:"password,example:123456"`         // 密码
}

type LoginResp struct {
	Token string `json:"token"` //  token
}

type UserInfoReq struct {
	Id int64 `path:"id,example:3"` // 用户id
}

type UserReq struct {
	Name     string `json:"name,example:admin"`              // 用户名
	Email    string `json:"email,example:admin@example.com"` // 邮箱
	Password string `json:"password,example:123456"`         // 密码
}

type UserResp struct {
	Name  string `json:"name"`  // 用户名
	Email string `json:"email"` // 邮箱
}
